server:
  shutdown: graceful
  tomcat:
    mbeanregistry:
      enabled: true
  error:
    include-exception: true
    include-stacktrace: never

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
      base-path: /

spring:
  jmx:
    enabled: true

logging:
  level:
    root: INFO

hawtio:
  authenticationEnabled: false
  proxyAllowlist: "*"