{
 "title": "HTTP Client Connections",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "app", "label": "app", "query": { "query": "label_values(up,app)" } }
  ]
 },
 "panels": [
  {
   "title": "Client Connections: Max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "httpcomponents_httpclient_pool_total_max{app=~\"$app\"}",
     "legendFormat": "{{app}}-{{version}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Client Connections: Default Max Per Route",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "httpcomponents_httpclient_pool_route_max_default{app=~\"$app\"}",
     "legendFormat": "{{app}}-{{version}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Client Connections: Pending",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "httpcomponents_httpclient_pool_total_pending{app=~\"$app\"}",
     "legendFormat": "{{app}}-{{version}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Client Connections: Available",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "httpcomponents_httpclient_pool_total_connections{app=~\"$app\",state=\"available\"}",
     "legendFormat": "{{app}}-{{version}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Client Connections: Leased",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "httpcomponents_httpclient_pool_total_connections{app=~\"$app\",state=\"leased\"}",
     "legendFormat": "{{app}}-{{version}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Server Connections: Average Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_sum{app=~\"$app\"} / http_server_requests_seconds_count{app=~\"$app\"}",
     "legendFormat": "{{app}}-{{version}} ({{instance}}) ({{method}} {{uri}}) ({{status}})"
    }
   ]
  },
  {
   "title": "Server Connections: Completions in last Minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{app=~\"$app\"} - http_server_requests_seconds_count{app=~\"$app\"} offset 1m",
     "legendFormat": "{{app}}-{{version}} ({{instance}}) ({{method}} {{uri}}) ({{status}})"
    }
   ]
  }
 ]
}