{
 "title": "HTTP Connections",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "service", "label": "service", "query": { "query": "label_values(up,service)" } },
   {
    "name": "http_server_uri",
    "label": "http_server_uri",
    "query": {
     "query": "label_values(http_server_requests_seconds_bucket{service=~\"$service\"},uri)"
    }
   },
   {
    "name": "http_client_uri",
    "label": "http_client_uri",
    "query": {
     "query": "label_values(http_client_requests_seconds_bucket{service=~\"$service\"},uri)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Server Connections (Tomcat)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tomcat: Threads",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tomcat_threads_current_threads{service=~\"$service\"}",
       "legendFormat": "{{service}}#{{version}}@{{instance}}: {{method}} {{uri}} (current)"
      },
      {
       "expr": "tomcat_threads_busy_threads{service=~\"$service\"}",
       "legendFormat": "{{service}}#{{version}}@{{instance}}: {{method}} {{uri}} (busy)"
      }
     ]
    },
    {
     "title": "Tomcat: Threads Max",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tomcat_threads_config_max_threads{service=~\"$service\"}",
       "legendFormat": "{{service}}#{{version}}@{{instance}}: {{method}} {{uri}}"
      }
     ]
    },
    {
     "title": "Tomcat: Open Connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tomcat_connections_current_connections{service=~\"$service\"}",
       "legendFormat": "{{service}}#{{version}}@{{instance}}: (total)"
      },
      {
       "expr": "tomcat_connections_keepalive_current_connections{service=~\"$service\"}",
       "legendFormat": "{{service}}#{{version}}@{{instance}}: (keepAlive)"
      }
     ]
    },
    {
     "title": "Tomcat: Max Open Connections",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tomcat_connections_config_max_connections{service=~\"$service\"}",
       "legendFormat": "{{service}}#{{version}}@{{instance}}"
      }
     ]
    },
    {
     "title": "Tomcat: Active Sessions",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "tomcat_sessions_active_current_sessions{service=~\"$service\"}",
       "legendFormat": "{{service}}#{{version}}@{{instance}}"
      }
     ]
    },
    {
     "title": "Tomcat: Sessions Expiration Rate",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(tomcat_sessions_expired_sessions_total{service=~\"$service\"}[1m])",
       "legendFormat": "{{service}}#{{version}}@{{instance}}"
      }
     ]
    },
    {
     "title": "Tomcat: Max Alive Session Duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "tomcat_sessions_alive_max_seconds{service=~\"$service\"}",
       "legendFormat": "{{service}}#{{version}}@{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Server Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server Connections: Completed Requests Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(http_server_requests_seconds_count{service=~\"$service\"}[1m])",
       "legendFormat": "{{service}}#{{version}}@{{instance}}: {{method}} {{uri}} ({{status}})"
      }
     ]
    },
    {
     "title": "Server Connections: Request Duration Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(http_server_requests_seconds_sum{service=~\"$service\"}[1m])",
       "legendFormat": "{{service}}#{{version}}@{{instance}}: {{method}} {{uri}} ({{status}}) (total)"
      },
      {
       "expr": "irate(http_server_requests_seconds_sum{service=~\"$service\"}[1m]) / irate(http_server_requests_seconds_count{service=~\"$service\"}[1m])",
       "legendFormat": "{{service}}#{{version}}@{{instance}}: {{method}} {{uri}} ({{status}}) (avg per request)"
      }
     ]
    },
    {
     "title": "Server Connections: Duration/Request",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "http_server_requests_seconds_max{service=~\"$service\"}",
       "legendFormat": "{{service}}#{{version}}@{{instance}}: {{method}} {{uri}} ({{status}}) (max)"
      },
      {
       "expr": "http_server_requests_seconds_sum{service=~\"$service\"} / http_server_requests_seconds_count{service=~\"$service\"}",
       "legendFormat": "{{service}}#{{version}}@{{instance}}: {{method}} {{uri}} ({{status}}) (avg since start of app)"
      }
     ]
    }
   ]
  },
  {
   "title": "Server Latency Histogram",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Server Request Latency: $http_server_uri (SUCCESS)",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
     "repeat": "http_server_uri",
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_bucket{service=~\"$service\",uri=~\"$http_server_uri\",outcome=\"SUCCESS\"}[$__interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Server Request Latency: $http_server_uri (ERROR)",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "repeat": "http_server_uri",
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_bucket{service=~\"$service\",uri=~\"$http_server_uri\",outcome!=\"SUCCESS\"}[$__interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Server Request Latency: $http_server_uri (SUCCESS)",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_bucket{service=~\"$service\",uri=~\"$http_server_uri\",outcome=\"SUCCESS\"}[$__interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Server Request Latency: $http_server_uri (ERROR)",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "sum(increase(http_server_requests_seconds_bucket{service=~\"$service\",uri=~\"$http_server_uri\",outcome!=\"SUCCESS\"}[$__interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    }
   ]
  },
  {
   "title": "TaskExecutor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Executor: Queued Tasks",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "executor_queued_tasks{service=~\"$service\"}",
       "legendFormat": "{{service}}#{{version}}@{{instance}}: {{ name }}"
      }
     ]
    },
    {
     "title": "Executor: Queue Remaining Tasks",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "executor_queue_remaining_tasks{service=~\"$service\"}",
       "legendFormat": "{{service}}#{{version}}@{{instance}}: {{ name }}"
      }
     ]
    },
    {
     "title": "Executor: Completed Tasks Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 4 },
     "yaxes": [
      { "format": "pps" }
     ],
     "targets": [
      {
       "expr": "irate(executor_completed_tasks_total{service=~\"$service\"}[1m])",
       "legendFormat": "{{service}}#{{version}}@{{instance}}: {{ name }}"
      }
     ]
    },
    {
     "title": "Executor: Pool Size Threads",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "executor_pool_size_threads{service=~\"$service\"}",
       "legendFormat": "{{service}}#{{version}}@{{instance}}: {{ name }}"
      }
     ]
    },
    {
     "title": "Executor: Pool Core Threads",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "executor_pool_core_threads{service=~\"$service\"}",
       "legendFormat": "{{service}}#{{version}}@{{instance}}: {{ name }}"
      }
     ]
    },
    {
     "title": "Executor: Pool Max Threads",
     "type": "graph",
     "description": "Additional threads are only added if queue has no remaining elements.",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 13 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "executor_pool_max_threads{service=~\"$service\"}",
       "legendFormat": "{{service}}#{{version}}@{{instance}}: {{ name }}"
      }
     ]
    },
    {
     "title": "Executor: Task Idle Duration Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(executor_idle_seconds_sum{service=~\"$service\"}[1m])",
       "legendFormat": "{{service}}#{{version}}@{{instance}}: {{ name }} (total)"
      },
      {
       "expr": "irate(executor_idle_seconds_sum{service=~\"$service\"}[1m])/(executor_queued_tasks{service=~\"$service\"}>0)",
       "legendFormat": "{{service}}#{{version}}@{{instance}}: {{ name }} (avg per task)"
      }
     ]
    },
    {
     "title": "Executor: Task Idle Seconds/Task",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "executor_idle_seconds_max{service=~\"$service\"}",
       "legendFormat": "{{service}}#{{version}}@{{instance}}: {{ name }} (max)"
      },
      {
       "expr": "executor_idle_seconds_sum{service=~\"$service\"} / executor_idle_seconds_count{service=~\"$service\"}",
       "legendFormat": "{{service}}#{{version}}@{{instance}}: {{ name }} (avg since start of app)"
      }
     ]
    },
    {
     "title": "Executor: Task Active Duration Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(executor_seconds_sum{service=~\"$service\"}[1m])",
       "legendFormat": "{{service}}#{{version}}@{{instance}}: {{ name }} (total)"
      },
      {
       "expr": "irate(executor_seconds_sum{service=~\"$service\"}[1m])/(executor_pool_size_threads{service=~\"$service\"}>0)",
       "legendFormat": "{{service}}#{{version}}@{{instance}}: {{ name }} (avg per task)"
      }
     ]
    },
    {
     "title": "Executor: Task Active Seconds/Task",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "executor_seconds_max{service=~\"$service\"}",
       "legendFormat": "{{service}}#{{version}}@{{instance}}: {{ name }} (max)"
      },
      {
       "expr": "executor_seconds_sum{service=~\"$service\"} / executor_seconds_count{service=~\"$service\"}",
       "legendFormat": "{{service}}#{{version}}@{{instance}}: {{ name }} (avg since start of app)"
      }
     ]
    }
   ]
  },
  {
   "title": "Client Connections (Apache Client)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Client Connections: Max",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "httpcomponents_httpclient_pool_total_max{service=~\"$service\"}",
       "legendFormat": "{{service}}#{{version}}@{{instance}}: {{ httpclient }}"
      }
     ]
    },
    {
     "title": "Client Connections: Max Per Route",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "httpcomponents_httpclient_pool_route_max_default{service=~\"$service\"}",
       "legendFormat": "{{service}}#{{version}}@{{instance}}: {{ httpclient }}"
      }
     ]
    },
    {
     "title": "Client Connections: Pending",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "httpcomponents_httpclient_pool_total_pending{service=~\"$service\"}",
       "legendFormat": "{{service}}#{{version}}@{{instance}}: {{ httpclient }}"
      }
     ]
    },
    {
     "title": "Client Connections: Leased",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "httpcomponents_httpclient_pool_total_connections{service=~\"$service\",state=\"leased\"}",
       "legendFormat": "{{service}}#{{version}}@{{instance}}: {{ httpclient }}"
      }
     ]
    },
    {
     "title": "Client Connections: Available",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "httpcomponents_httpclient_pool_total_connections{service=~\"$service\",state=\"available\"}",
       "legendFormat": "{{service}}#{{version}}@{{instance}}: {{ httpclient }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Client Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Client Requests: Completed Requests Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(http_client_requests_seconds_count{service=~\"$service\"}[1m])",
       "legendFormat": "{{method}} {{uri}} ({{status}})"
      }
     ]
    },
    {
     "title": "Client Requests: Request Duration Rate",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "irate(http_client_requests_seconds_sum{service=~\"$service\"}[1m])",
       "legendFormat": "{{method}} {{uri}} ({{status}}) (total)"
      },
      {
       "expr": "irate(http_client_requests_seconds_sum{service=~\"$service\"}[1m]) / irate(http_client_requests_seconds_count{service=~\"$service\"}[1m])",
       "legendFormat": "{{method}} {{uri}} ({{status}}) (avg per request)"
      }
     ]
    },
    {
     "title": "Client Requests: Duration/Request",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "http_client_requests_seconds_max{service=~\"$service\"}",
       "legendFormat": "{{method}} {{uri}} ({{status}}) (max)"
      },
      {
       "expr": "http_client_requests_seconds_sum{service=~\"$service\"} / http_client_requests_seconds_count{service=~\"$service\"}",
       "legendFormat": "{{method}} {{uri}} ({{status}}) (avg since start of app)"
      }
     ]
    }
   ]
  },
  {
   "title": "Client Latency Histogram",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Client Request Latency: $http_client_uri (SUCCESS)",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
     "repeat": "http_client_uri",
     "targets": [
      {
       "expr": "sum(increase(http_client_requests_seconds_bucket{service=~\"$service\",uri=~\"$http_client_uri\",outcome=\"SUCCESS\"}[$__interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Client Request Latency: $http_client_uri (ERROR)",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
     "repeat": "http_client_uri",
     "targets": [
      {
       "expr": "sum(increase(http_client_requests_seconds_bucket{service=~\"$service\",uri=~\"$http_client_uri\",outcome!=\"SUCCESS\"}[$__interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    }
   ]
  }
 ]
}