target:
  server:
    url: http://localhost:8600

server:
#  port: 8080
  shutdown: graceful
#  http2:
#    enabled: true
#  netty:
#    connection-timeout:
  error:
    include-exception: true
    include-stacktrace: never

netty:
  event-loop:
    metrics: true
#    select-count: -1
#    worker-count: 8
  http-server:
    protocols: http11
  http-client:
    protocols: http11
#    connect-timeout: 1s
#    socket-timeout: 5s
#    response-timeout: 10s
#    connection:
#      max-connections: 500
#      pending-acquire-max-count: -1
#      pending-acquire-timeout: 45s
#      leasing-strategy: fifo
#      max-idle-time: 5m
#      max-life-time: 1d

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  metrics:
    distribution:
      slo:
        http.server.requests: 10ms,50ms,100ms,250ms,500ms,750ms,1s,2s,5s,10s,15s,20s,30s,60s
        http.client.requests: 10ms,50ms,100ms,250ms,500ms,750ms,1s,2s,5s,10s,15s,20s,30s,60s

spring:
  jmx:
    enabled: true

logging:
  level:
    root: INFO