server:
  #  port: 8080
  shutdown: graceful
  #  http2:
  #    enabled: true
  #  netty:
  #    connection-timeout:
  error:
    include-exception: true
    include-stacktrace: never

netty:
  event-loop:
    metrics: true
  #    select-count: -1
  #    worker-count: 8
  http-server:
    protocols: http11

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  metrics:
    distribution:
      slo:
        http.server.requests: 10ms,50ms,100ms,500ms,1s,2s,5s,10s,15s,20s,30s,45s,60s

spring:
  jmx:
    enabled: true

logging:
  level:
    root: INFO