service:
  url:
    http11-server: http://localhost:8600

server:
  error:
    include-exception: true
    include-stacktrace: never

#spring:
#  task:
#    execution:
#      pool:
#        core-size: 8
#        # max-size and queue-capacity should be configured together, because new threads are only created if queue is full.
#        max-size: 2147483647
#        queue-capacity: 2147483647
#        keep-alive: 60s
#        allow-core-thread-timeout: true

http:
  client:
    use-default-request-factory: true
#    pool:
#      max-connections-total: 20
#      default-max-connections-per-route: 2
#      time-to-live: 0s
#      keep-alive: true
#    request:
#      connection-request-timeout: 0
#      connect-timeout: 0
#      socket-timeout: 0

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "*"
  metrics:
    distribution:
      slo:
        http.server.requests: 10ms,50ms,100ms,250ms,500ms,750ms,1s,2s,5s,10s,15s,20s,30s,60s
        http.client.requests: 10ms,50ms,100ms,250ms,500ms,750ms,1s,2s,5s,10s,15s,20s,30s,60s

spring:
  jmx:
    enabled: true

logging:
  level:
    root: INFO
    org.apache.http.impl.conn.PoolingHttpClientConnectionManager: INFO