:toc:
:toc-title:
:toclevels: 2
:sectnums:

= HTTP/1.1 Delegate with Spring Web using RestTemplate and Connection Pool

This application accepts requests at `GET /delegate/demo/` and forwards this requests to `GET /demo` endpoint of `http11-server` app using Spring's _RestTemplate_.

== Quick Start

.Build Image
[source,bash]
----
./gradlew :http11-delegate:bootBuildImage
----

.Run
[source,bash]
----
SERVER_PORT=8900 ./gradlew :http11-delegate:bootRun
----

.Query
[source,bash]
----
time curl -v http://localhost:8900/delegate/demo &
----

.Metrics
[source,bash]
----
curl -v http://curl -s http://localhost:8900/actuator/prometheus
----

== Implementation

=== Server

This application accepts _HTTP/1.1_ requests. To provide this capability this application depends `org.springframework.boot:spring-boot-starter-web` which in turn depends on `org.springframework.boot:spring-boot-starter-tomcat` which uses an embedded _Tomcat_.

The _Tomcat_ server can be configured in the link:src/main/resources/application.yaml:[application.yaml] file.

.Important configs with default values
[source,yaml]
----
server:
  port: 8080
  tomcat:
    accept-count: 100
    max-connections: 8192
    threads:
      max: 200
      min-spare: 10
    connection-timeout: 60000
    mbeanregistry:
      enabled: true
----

The configuration options are described very well in those blog posts:

* https://www.programmersought.com/article/89248083515/
* https://www.baeldung.com/spring-boot-configure-tomcat

The official _Tomcat_ config documentation can be found at: https://tomcat.apache.org/tomcat-9.0-doc/config/http.html

=== Monitoring

In order to enable additional server metrics, enable MBeans for Tomcat:

[source,yaml]
----
server:
  tomcat:
    mbeanregistry:
      enabled: true
----

This exposes additional metrics in addition to `tomcat_sessions_*`.

=== Client

=== Task Thread Pool

https://www.baeldung.com/java-threadpooltaskexecutor-core-vs-max-poolsize

The `ThreadPoolTaskExecutor` delegates its value to the underlying `ThreadPoolExecutor`. The `ThreadPoolExecutor` will only create a new thread when the queue is full up to the maximum pool size.